### PR TITLE
341 oidc bug

### LINKED ISSUE #341: OIDC Plugin test case failing
`gluu-openid-connect` plugin lua test case failing. It goes for refresh token as well as for silent authentication.

```
2019/07/30 08:18:54 [debug] 41#0: *57 [kong] access.lua:177 [gluu-openid-connect] access_token refreshed: 88bba7f5-961c-4b71-8053-9ab35f1ad333 updated refresh_token: 33d7988e-6ffb-4fe5-8c2a-0e158691d333
2019/07/30 08:18:54 [debug] 41#0: *57 [kong] access.lua:321 [gluu-openid-connect] session.present=true, session.data.id_token=true, token_expired=false
2019/07/30 08:18:54 [debug] 41#0: *57 [kong] access.lua:347 [gluu-openid-connect] Silent authentication is required - Redirecting to OP Authorization endpoint
2019/07/30 08:18:54 [debug] 41#0: *57 [kong] kong-common.lua:69 [gluu-openid-connect] Current datetime: 1564474734.288 access_token.expire: 1564475018.235

```

### PR DESCRIPTION
**Pull request by altexy**
Close #341 

This was not really bug, but one misconfiguration and wrong scenario.

Now all our plugins use refresh tokens (if any) to update access_token for oxd access.

We wrongly used the `max_id_token_age` for OIDC access token (get_user_info) also, fixed in a consistent way as oxd access tokens.

The test scenario and model have fixed, test both id_token silent refresh and get access_token by refresh token use cases.

### CODE REVIEW

File: t/specs/gluu-openid-connect/test_spec.lua [hunk 1]
```diff
@@ -219,24 +219,34 @@ test("basic", function()
...
         [[ -b ]], cookie_tmp_filename)
     assert(res:find("200", 1, true))
     assert(res:find("x-openid-connect-idtoken", 1, true))
     assert(res:find("x-openid-connect-userinfo", 1, true))
 
-    sh_ex("sleep 15");
-    print"Failed to get new access token, go for authentication"
+    sh_ex("sleep 6");
+
+    print"id_token is expired, require silent reauth"
```
Comment (ldeveloperl1985) [inline t/specs/gluu-openid-connect/test_spec.lua]: One Question:
Application successfully gets the `access_token_by_refresh_token` and refresh the session that means the user has valid access_token for the next 60 sec(mock test case response). but just after 6 seconds because of id_token expired `(id_token.iat + conf.max_id_token_age) < ngx.time()` config and it is going for re-auth code flow which I think wrong and not getting the use of `conf.max_id_token_age` in this case. so not sure I am wrong or right. If I am wrong please correct me.

Comment (altexy) [reply t/specs/gluu-openid-connect/test_spec.lua]: The model1 responds on `/get-tokens-by-code` (#4) with `expires_in = 10`.
This value is about of expiration of `access_token`, not id_token. It is intentionally made very short (sorry the comment in test_spec is wrong, will fix it). 
The expiration of id_token is defined by `response.id_token_claims.exp = ngx.time() + 60`

**Comment by altexy** [comment]
@ldeveloperl1985 I have removed access token in user session and refresh code.
Test suite also updated.
